version: "3.8"
services:
  rs-wg:
    image: yamzeg/rs-wg
    container_name: rs-wg
    environment:
      - WIREGUARD_SETTINGS=/etc/wireguard/settings.json
      - WIREGUARD_PATH=/etc/wireguard
      - STATIC_DIR=/etc/www/
      - RUST_LOG=actix_web=warn,debug

      # optional parameters are commented out
      # - INTERFACE_NAME=wg0
      # - RELEASE=rs0
      # - API_PORT=8080
      # - PASSWORD=123321
      - HOST=localhost
      - WG_PORT=51820
      # - MTU=0
      # - PERSISTENT_KEEPALIVE=25
      # - DEFAULT_ADDRESS=10.8.0.1
      # - DEFAULT_ADDRESS_BASE=10.8.0
      # - DEFAULT_DNS=1.1.1.1
      # - ALLOWED_IPS=0.0.0.0/0, ::/0
      # - PRE_UP=
      # - POST_UP=
      # - PRE_DOWN=
      # - POST_DOWN=
    volumes:
      - ./data:/etc/wireguard
    ports:
      - "51820:51820/udp" # should be same as WG_PORT
      - "8080:8080/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    entrypoint: dumb-init /usr/local/cargo/bin/rs-wg
